
= Kirjoitustehtävä ravinnon merkityksestö

== Ravinto ja suun terveys

Ravinnolla on suuri merkitys suun terveydelle. Ravinto vaikuttaa hampaisiin, vaikka hampaat olisivat täysin terveet, puhkeamassa tai jo puhjenneet. Myös hampaattomaan suuhun vaikuttaa ravinto, koska 
myös silloin suun limakavot ovat yhteydessä ravintoon. Suuhun tuotua ruokaa ei ole vielä käsitelty elimistössä joten hampaat ja ikenet kohtaavat ravinnon sellaisenaan.

Suun terveyden kannalta on tärkeää mitä syö. Ravinnon vaikutus suun teyrveyteen riippuu ravinnon koostumuksesta. Myös ruokailukertojen määrä liittyy suun terveyteen. Koostumus ja ruokailukerrat voivat edistää tai heikentää suun terveyttä.

Suun terveyttävää ravintoa voisi olla esimerkiksi fluoria, kalsimuia ja fosfaattia sisältävä ruoka. Ruoka, jonka syömisessä tarvitaan pureskelua edistää myös suun terveyttä. Vastakohtana taas suun terveyttä heikentää sokerillinen ja hapokas ravinto. Jos ihmisellä on ruokaaineallergioita, niin jotkin allergisoivat ruoka-aineet voivat myös heikentää suun terveyttä.

    Lähde:
    (https://www.terveysportti.fi/apps/dtk/tod/article/trv00012?toc=403594)

== Suun terveys ja syömistottumukset

Nykymaailmassamme huonot ja suun terveyden kannalta haitalliset syömistottumukset ovat yleistyneet laajasti. Ravinnon saantia ei ole jaksotettu oikein vaan ruokailujen välille ei jää tarpeeksi taukoa. 

Tiheät syömisvälit tuovat jatkuvasti happohyökkäyksiä suuhun. Hampaat ja limakalvot eivät saa taukoa, mikä johtaa hampaiden reikiintymiseen.

Napostelukulttuurille on yleistä, että suuhun tuodaan jatkuvasti sokeria, suolaa, rasvaa ja energiaa. Kunnollisen ruuan sijaan, napostelavaa ravintoa on helppo ostaa. Erityisesti lasten ja nuorten hampaat ovat alttiita napostelun terveyshaitoille.

Pureskeltava ruoka lisää syljeneritystä suussa. Sylki taas kovettaa happojen liottamaa kiillettä. Ravinto, jota pitää pureskella on siis parempaa kuin pehmeä ravinto.

Sokerien ja happojen nauttiminen johtaa hammaspintojen kulumiseen. Pintojen ohentumisesta aiheutuu hampaiden vihlontaa, suun kipuja ja lohkeilua.

Suun terveyttä voi ylläpitää syömällä monipuolisesti. Ravinnon tulisi olla pureskeltavaa ja syöminen kuuluisi ajoittaa niin, että syömiskertojen välille jäisi aikaa noin 2–3 tuntia.

Hyvien syomistottumusten ylläpitoa voi helpottaa syömällä säännöllisesti riittävän suuria aterioita. Nälkäisyys voi jphtaa helposti naposteluun.

Aterian syötyään voi ottaa ksylitolia tai jotain kalsiumia runsaasti sisältävää ruokaa.

    Lähde:
    (https://www.terveysportti.fi/apps/dtk/tod/article/trv00163/search/Suun%20terveys%20ja%20sy%C3%B6mistottumukset)