
= Kirjoitustehtävä ravinnon merkityksestö

== Ravinto ja suun terveys

Ravinnolla on suuri merkitys suun terveydelle. Ravinto vaikuttaa hampaisiin, vaikka hampaat olisivat täysin terveet, puhkeamassa tai jo puhjenneet. Myös hampaattomaan suuhun vaikuttaa ravinto, koska 
myös silloin suun limakavot ovat yhteydessä ravintoon. Suuhun tuotua ruokaa ei ole vielä käsitelty elimistössä joten hampaat ja ikenet kohtaavat ravinnon sellaisenaan.

Suun terveyden kannalta on tärkeää mitä syö. Ravinnon vaikutus suun teyrveyteen riippuu ravinnon koostumuksesta. Myös ruokailukertojen määrä liittyy suun terveyteen. Koostumus ja ruokailukerrat voivat edistää tai heikentää suun terveyttä.

Suun terveyttävää ravintoa voisi olla esimerkiksi fluoria, kalsimuia ja fosfaattia sisältävä ruoka. Ruoka, jonka syömisessä tarvitaan pureskelua edistää myös suun terveyttä. Vastakohtana taas suun terveyttä heikentää sokerillinen ja hapokas ravinto. Jos ihmisellä on ruokaaineallergioita, niin jotkin allergisoivat ruoka-aineet voivat myös heikentää suun terveyttä.

Lähde:
https://www.terveysportti.fi/apps/dtk/tod/article/trv00012?toc=403594

== Suun terveys ja syömistottumukset

Nykymaailmassamme huonot ja suun terveyden kannalta haitalliset syömistottumukset ovat yleistyneet laajasti. Ravinnon saantia ei ole jaksotettu oikein vaan ruokailujen välille ei jää tarpeeksi taukoa. 

Tiheät syömisvälit tuovat jatkuvasti happohyökkäyksiä suuhun. Hampaat ja limakalvot eivät saa taukoa, mikä johtaa hampaiden reikiintymiseen.

Napostelukulttuurille on yleistä, että suuhun tuodaan jatkuvasti sokeria, suolaa, rasvaa ja energiaa. Kunnollisen ruuan sijaan, napostelavaa ravintoa on helppo ostaa. Erityisesti lasten ja nuorten hampaat ovat alttiita napostelun terveyshaitoille.

Pureskeltava ruoka lisää syljeneritystä suussa. Sylki taas kovettaa happojen liottamaa kiillettä. Ravinto, jota pitää pureskella on siis parempaa kuin pehmeä ravinto.

Sokerien ja happojen nauttiminen johtaa hammaspintojen kulumiseen. Pintojen ohentumisesta aiheutuu hampaiden vihlontaa, suun kipuja ja lohkeilua.

Suun terveyttä voi ylläpitää syömällä monipuolisesti. Ravinnon tulisi olla pureskeltavaa ja syöminen kuuluisi ajoittaa niin, että syömiskertojen välille jäisi aikaa noin 2–3 tuntia.

Hyvien syomistottumusten ylläpitoa voi helpottaa syömällä säännöllisesti riittävän suuria aterioita. Nälkäisyys voi jphtaa helposti naposteluun.

Aterian syötyään voi ottaa ksylitolia tai jotain kalsiumia runsaasti sisältävää ruokaa. Pureskeltavat pähkinät ovat varsin hyvä pikkupurtava aterian jälkeen. 

Lähde:
https://www.terveysportti.fi/apps/dtk/tod/article/trv00163/search/Suun%20terveys%20ja%20sy%C3%B6mistottumukset

== Ravinnon sokerit ja suun terveys

Suun terveyden kannalta pahimpia hiilihydraatteja ovat sokerit. Sokerit heikentävät hampaiden terveyttä, koska suussa olevat bakteerit käyttävät ravinnon mukana tulleista sokereista happoja. Hampaille hapot ovat haitallisia, koska ne laskevat hampaiden pH:ta eli happamuutta. Hampaiden kiille alkaa liukenamaan kun happamuus laskee tarpeeksi. 

Suussa oleva sylki korjaa sokereiden tekemää haittaa. Korjautuminen ei kutenkaan tapahdu jos suussa on meneillään happohyökkäys. Siksi sokeria ei saisi syödä jatkuvalla tahdilla. 

Jos hampaiden pinta pehmenee liikaa ja sylki ei ehdi kovettaa kiillettä niin hampaisiin muodostuu reikä. 

Melkein kaikki ravinto sisältää hiilihydraatteja, joita suun bakteerit käyttävät ravintonaan. Kaikista pahimia happojen muodostajia ovat sakkaroosi, glukoosi, fruktoosi, maltoosi, laktoosi ja tärkkelyssiirapit. 

Ksylitoli ja erytritoli ovat happaille vaarattomia luonnonmukaisia sokereita. Aspartaami, asesulfaami K, sukraloosi ja sakariini ovat hampaiden kannalta haitattomia keinotekoisia makeuttajia. Näillä makeuttajillla makeutetut tuotteet voivat silti aiheuttaa eroosiota hampaissa, jos tuotteissa on muuten vain happoja.

Ksylitoli on erityinen sokeri, koska sillä on jopa positiivisia vaikutteita hampaiden terveyteen. Ksylitolia on tutkittu ja sen on todettu voivan estää hampaiden reikien muodostumista. 

Sokerien aiheuttamaan haittaan vaikuttaa se kauanko ne viipyvät suussa. Kauemmin viipyneet sokerit aiheuttavat enemmän happojen muodostumista. 

Sokereita voi jäädä suuhun pidemmäksi aikaa jos hampaista löytyy epätasaisuuksia. Sokeri voi myös tarttua hampaisiin ja jäädä siksi sinne pidemmäksi aikaa. Reiät ja lohkeamat saattavat kerätä sokereita. Myös oikomislaitteet ja irtoproteesit tekevät samaa.

Sokerien poistumista auttavat hyvä syljeneritys, pureskelu ja sokerin liukeneminen. Ksylitoli auttaa sokerista johtuvan hapon poistumista ja on siksi hyväksi suulle aterian jälkeen nautittuna.

lähde:
https://www.terveysportti.fi/apps/dtk/tod/article/trv00014/search/Ravinnon%20happamuus%20ja%20hampaiden%20eroosio

== Ravinnon happamuus ja hampaiden eroosio

Hammaskiilteen kemiallista syöpymistä kutsutaan eroosioksi. Eroosiota ei sii ole esimerkiksi bakteeritoiminnasta syntyvä happohyökkäys.

Kaikki happamat aineet voi aiheuttaa eroosiota. Happaman aineen koskettaessa hammaskiillettä tai hammasluuta voi aiheuttaa niissä eroosiota. 

Lääkkeet ja ihmisen luonnolliset toiminnallisuudet kuten oksentaminen ja vatsahappo-oireet voivat myös aiheuttaa eroosiota. 

Suun kuivuus suurentaa riskiä eroosioon huomattavasti. Kuivuus saa ruuan ja juoman pysymään pidempään hampaiden pinnalla. Tästä syystä johtuen esimerkiksi urheilijat ovat alttiimpia eroosiolle.

Eroosiota voi ehkäistä välttelemällä happamia ruokia ja juomia. Sokerin kulutusta kannattaa myös välttää.



Lähde:
https://www.terveysportti.fi/apps/dtk/tod/article/trv00015/search/Ravinnon%20happamuus%20ja%20hampaiden%20eroosio

== Juomat ja suun terveys

Juomat voivat edistää tai olla haitaksi suun terveydelle. Juomat itsessään voivat olla happamia ja heikentää hampaiden kuntoa. Toisaalta kuiva suu kasvattaa riskiä eroosioon ja juoma voi liuettaa sokereita pois suusta.

On mahdollista, että juomat tuovat suuhun suun terveyttä edistäviä aineita kuten fluoria, kalsiumia tai muita rakennusaineita. Juomilla voidaan myös neutralisoida suussa olevaa happamuutta.

Juomat voivat kuitenkin sisältää runsaasti sokereita ja olla hyvinkin hapokkaita. Tyypillisesti juomia juodaan siemailen jolloin hampaat ovat jatkuvan happohyökkäyksen alla. 

Juomia kannattaisi juoda suuri määrä kerrallaan, jotta juominen ei pitkittyisi ja happohyökkäyksen kesto lyhenisi. Juomien käyttötavoilla voi siis vaikuttaa juomien aiheuttamaan suun haittaan. Myös keinomakeutetut juomat aiheuttavat eroosiota, koska sokerin poistaminen ei poista hapokkuutta.

Alle 15-vuotialle lapsille hapokkaiden juomien nauttiminen on erityisen haitallista, koska heidän hampaansa ovat vielä kehittymisvaiheessa.

Lähde:
https://www.terveysportti.fi/apps/dtk/tod/article/trv00017/search/Juomat%20ja%20suun%20terveys

== Kasvisruokavalio ja suun terveys

Eräiden tutkimusten mukaan kasviksiin ja maitotuotteisiin koostuvien dieettien syöjissä eroosiota esiintyy jopa 77 %:lla. Luku on korkea verrattuna siihen että vain 10% sekasyöjistä todettiin eroosiota. 

Kasvisruokavalion etuna on pureskellessa syntyvä syljen eritys. Korkea eroosion ilmentyminen voi selittyä sillä, että kasvisruokavaliota noudattavat syövät useammin happamia marjoja ja hedelmiä.

Kasvisruokavaliossa mm.kalsiumin saanti voi olla vähäisempää, mikä voi johtaa luiden haurastumiseen.

Lähde:
https://www.terveysportti.fi/apps/dtk/tod/article/trv00016/search/kasvisruokavalio

== Erityisruokavaliot ja suun terveys

=== Laktoosi-intorelanssi ja maitoallergiat
Laktoosi-intorelanssipotilaiden keskuudessa ei olla huomattu eroja kariesin esiintymisessä, mutta maitoallergia saattaa vaikuttaa suun terveyteen. Maitoallergiapotilailla saattaa ilmetä hetkellistä hypokalsemiaa, joka johtaa hampaiden terveyden heikkenemiseen. 

Maitoallergikot saattavat käyttää hoidossaan purutabletteja ja annosjauheita, jotka sisältävät suun terveyttä vaarantavia aineita. Allergian hoidossa näitä aineita saatetaan käyttää useita kertoja päivässä.

=== Paastoaminen

Paatos saattaa muuttaa suun tilaa niin että suu altistuu haitoille. Esimerkiksi nestepaasto kuivattaa suuta, mikä puolestaan mahdollistaa haitallisten ruoka-aineiden tarttumisen suuhun.

Paastoamisella voi olla vaikutusta syljen eritykseen, mikä heikentää syljen luonnollista happoja liuottavaa toiminnallisuutta.

Paastojen jatkuva harjoittaminen voi siis lisätä ihmisen riskiä kariekselle eli hampaiden reikiintymiselle ja eroosiolle.



Lähde:
https://www.terveysportti.fi/apps/dtk/tod/article/tod13006/search/Erityisruokavaliot%20